<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="CredentialApiMappers.fs" />
    <Compile Include="CredentialApiFactory.fs" />
    <Compile Include="SupplierApiMappers.fs" />
    <Compile Include="SupplierApiFactory.fs" />
    <Compile Include="TemplateApiMappers.fs" />
    <Compile Include="TemplateApiFactory.fs" />
    <Compile Include="MailAccountApiMappers.fs" />
    <Compile Include="MailAccountApiFactory.fs" />
    <Compile Include="InvoiceApiMappers.fs" />
    <Compile Include="ScanWindowApiMappers.fs" />
    <Compile Include="InvoiceApiFactory.fs" />
    <Compile Include="ScanWindowApiFactory.fs" />
    <Compile Include="Startup.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyDogsbody.Logging\MyDogsbody.Logging.fsproj" />
    <ProjectReference Include="..\MyDogsbody.UI.Types\MyDogsbody.UI.Types.fsproj" />
    <ProjectReference Include="..\MyDogsbody.Domain\MyDogsbody.Domain.fsproj" />
    <ProjectReference Include="..\MyDogsbody.Integrations.Credentials\MyDogsbody.Integrations.Credentials.fsproj" />
    <ProjectReference Include="..\MyDogsbody.Integrations.Thunderbird\MyDogsbody.Integrations.Thunderbird.fsproj" />
    <ProjectReference Include="..\MyDogsbody.Integrations.Documents\MyDogsbody.Integrations.Documents.fsproj" />
    <ProjectReference Include="..\MyDogsbody.Database\MyDogsbody.Database.fsproj" />
    <ProjectReference Include="..\MyDogsbody.Database.Migrations\MyDogsbody.Database.Migrations.fsproj" />
  </ItemGroup>

</Project>
