// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// Synthetic fixture for change #3 - a maildir-format account. SYNTHETIC ONLY (Q4.11): the real
// profile measured 2026-08-08 is 100% mbox (berkeleystore), so there is no real maildir to
// verify this shape against. See design.md -> Testing strategy -> Fixtures, and state this
// limitation in outcome.md rather than letting it be implied.

user_pref("mail.account.lastKey", 1);
user_pref("mail.accountmanager.accounts", "account1");

user_pref("mail.account.account1.identities", "id1");
user_pref("mail.account.account1.server", "server1");
user_pref("mail.server.server1.directory", "C:\\Users\\jygcn\\AppData\\Roaming\\Thunderbird\\Profiles\\maildir-shape\\Mail\\imap.maildir.example.com");
user_pref("mail.server.server1.directory-rel", "[ProfD]Mail/imap.maildir.example.com");
user_pref("mail.server.server1.hostname", "imap.maildir.example.com");
user_pref("mail.server.server1.name", "Maildir Mail");
user_pref("mail.server.server1.storeContractID", "@mozilla.org/msgstore/maildirstore;1");
user_pref("mail.server.server1.type", "imap");
user_pref("mail.server.server1.userName", "mallory");
user_pref("mail.identity.id1.useremail", "mallory@maildir.example.com");
user_pref("mail.identity.id1.fullName", "Mallory Maildir");
