// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// Synthetic fixture for change #3 (thunderbird-account-selection), reproducing every trap found
// in the real 16 GB profile measured 2026-08-08 - see
// docs/changes/invoice-to-calendar/background.md -> "The Thunderbird profile, measured".
//
// Ground truth for this fixture (Phase 3 tests are written against these exact facts):
//   - mail.account.lastKey = 20, but only 10 accounts exist: 1,2,3,6,9,10,17,18,19,20 -
//     gaps at 4,5,7,8,11-16. Iterating 1..lastKey must not invent an account at a gapped key.
//   - account20 is a Local Folders account (type "none") with NO identities - an account with
//     no identities must be listed with none, not dropped.
//   - account10 has TWO identities (id6, id7) on host imap.gamma.example.com.
//   - account9 (host imap.beta.example.com) has a STALE absolute `directory` pointing at a user
//     path that does not exist, alongside a correct `directory-rel` that resolves under this
//     fixture root. Resolution must use directory-rel, never the absolute value.
//   - account17 (host imap.delta.example.com) resolves to ImapMail/imap.delta.example.com,
//     which is deliberately never created on disk - configured-but-missing.
//   - account18's display name contains an escaped embedded quote, to exercise decode
//     correctness of prefs.js string escaping.
//   - Accounts 1, 2, 6 (wait: 1, 2, 3, 6) sit on one host family with a numeric infix -
//     imap.alpha.example.com, imap.alpha-1.example.com, imap.alpha-2.example.com,
//     imap.alpha-3.example.com - four distinct accounts that a directory-name-based scan would
//     wrongly try to disambiguate by name instead of by prefs.js account key.
//   - Under ImapMail/, 14 real directories exist: 8 accounted for by an account's directory-rel
//     (alpha, alpha-1, alpha-2, alpha-3, beta, gamma, epsilon, zeta) and 6 pure orphans with no
//     account pointing at them (imap.orphan1..6.example.com) - orphan1 is padded so it is not
//     empty, echoing the real profile's 2 GB orphan Deleted file. delta (account17's target) is
//     a 15th, referenced-but-absent directory.
//   - imap.alpha.example.com/ carries the rest of the shapes: Music.sbd nesting three levels
//     deep (Music -> "Surrey Hills Orchestra" -> Rehearsals), Trash/Junk/Sent/Drafts present and
//     sized (excluded from scanning), and two .msf files (Archives.msf, OldStuff.msf) with no
//     matching mbox file at all.

user_pref("mail.account.lastKey", 20);
user_pref("mail.accountmanager.accounts", "account1,account2,account3,account6,account9,account10,account17,account18,account19,account20");

// ---------- account1 / server1 - imap.alpha.example.com ----------
user_pref("mail.account.account1.identities", "id1");
user_pref("mail.account.account1.server", "server1");
user_pref("mail.server.server1.directory", "C:\\Users\\jygcn\\AppData\\Roaming\\Thunderbird\\Profiles\\measured-shape\\ImapMail\\imap.alpha.example.com");
user_pref("mail.server.server1.directory-rel", "[ProfD]ImapMail/imap.alpha.example.com");
user_pref("mail.server.server1.hostname", "imap.alpha.example.com");
user_pref("mail.server.server1.name", "Alpha Mail");
user_pref("mail.server.server1.storeContractID", "@mozilla.org/msgstore/berkeleystore;1");
user_pref("mail.server.server1.type", "imap");
user_pref("mail.server.server1.userName", "alice");
user_pref("mail.identity.id1.useremail", "alice@alpha.example.com");
user_pref("mail.identity.id1.fullName", "Alice Alpha");

// ---------- account2 / server2 - imap.alpha-1.example.com ----------
user_pref("mail.account.account2.identities", "id2");
user_pref("mail.account.account2.server", "server2");
user_pref("mail.server.server2.directory", "C:\\Users\\jygcn\\AppData\\Roaming\\Thunderbird\\Profiles\\measured-shape\\ImapMail\\imap.alpha-1.example.com");
user_pref("mail.server.server2.directory-rel", "[ProfD]ImapMail/imap.alpha-1.example.com");
user_pref("mail.server.server2.hostname", "imap.alpha-1.example.com");
user_pref("mail.server.server2.name", "Alpha Mail (2)");
user_pref("mail.server.server2.storeContractID", "@mozilla.org/msgstore/berkeleystore;1");
user_pref("mail.server.server2.type", "imap");
user_pref("mail.server.server2.userName", "bob");
user_pref("mail.identity.id2.useremail", "bob@alpha-1.example.com");
user_pref("mail.identity.id2.fullName", "Bob Alpha");

// ---------- account3 / server3 - imap.alpha-2.example.com ----------
user_pref("mail.account.account3.identities", "id3");
user_pref("mail.account.account3.server", "server3");
user_pref("mail.server.server3.directory", "C:\\Users\\jygcn\\AppData\\Roaming\\Thunderbird\\Profiles\\measured-shape\\ImapMail\\imap.alpha-2.example.com");
user_pref("mail.server.server3.directory-rel", "[ProfD]ImapMail/imap.alpha-2.example.com");
user_pref("mail.server.server3.hostname", "imap.alpha-2.example.com");
user_pref("mail.server.server3.name", "Alpha Mail (3)");
user_pref("mail.server.server3.storeContractID", "@mozilla.org/msgstore/berkeleystore;1");
user_pref("mail.server.server3.type", "imap");
user_pref("mail.server.server3.userName", "carol");
user_pref("mail.identity.id3.useremail", "carol@alpha-2.example.com");
user_pref("mail.identity.id3.fullName", "Carol Alpha");

// ---------- account6 / server4 - imap.alpha-3.example.com ----------
user_pref("mail.account.account6.identities", "id4");
user_pref("mail.account.account6.server", "server4");
user_pref("mail.server.server4.directory", "C:\\Users\\jygcn\\AppData\\Roaming\\Thunderbird\\Profiles\\measured-shape\\ImapMail\\imap.alpha-3.example.com");
user_pref("mail.server.server4.directory-rel", "[ProfD]ImapMail/imap.alpha-3.example.com");
user_pref("mail.server.server4.hostname", "imap.alpha-3.example.com");
user_pref("mail.server.server4.name", "Alpha Mail (4)");
user_pref("mail.server.server4.storeContractID", "@mozilla.org/msgstore/berkeleystore;1");
user_pref("mail.server.server4.type", "imap");
user_pref("mail.server.server4.userName", "dave");
user_pref("mail.identity.id4.useremail", "dave@alpha-3.example.com");
user_pref("mail.identity.id4.fullName", "Dave Alpha");

// ---------- account9 / server5 - imap.beta.example.com - STALE ABSOLUTE directory ----------
user_pref("mail.account.account9.identities", "id5");
user_pref("mail.account.account9.server", "server5");
user_pref("mail.server.server5.directory", "C:\\Users\\OldUser\\AppData\\Roaming\\Thunderbird\\Profiles\\measured-shape\\ImapMail\\imap.beta.example.com");
user_pref("mail.server.server5.directory-rel", "[ProfD]ImapMail/imap.beta.example.com");
user_pref("mail.server.server5.hostname", "imap.beta.example.com");
user_pref("mail.server.server5.name", "Beta Mail");
user_pref("mail.server.server5.storeContractID", "@mozilla.org/msgstore/berkeleystore;1");
user_pref("mail.server.server5.type", "imap");
user_pref("mail.server.server5.userName", "erin");
user_pref("mail.identity.id5.useremail", "erin@beta.example.com");
user_pref("mail.identity.id5.fullName", "Erin Beta");

// ---------- account10 / server6 - imap.gamma.example.com - TWO IDENTITIES ----------
user_pref("mail.account.account10.identities", "id6,id7");
user_pref("mail.account.account10.server", "server6");
user_pref("mail.server.server6.directory", "C:\\Users\\jygcn\\AppData\\Roaming\\Thunderbird\\Profiles\\measured-shape\\ImapMail\\imap.gamma.example.com");
user_pref("mail.server.server6.directory-rel", "[ProfD]ImapMail/imap.gamma.example.com");
user_pref("mail.server.server6.hostname", "imap.gamma.example.com");
user_pref("mail.server.server6.name", "Gamma Mail");
user_pref("mail.server.server6.storeContractID", "@mozilla.org/msgstore/berkeleystore;1");
user_pref("mail.server.server6.type", "imap");
user_pref("mail.server.server6.userName", "frank");
user_pref("mail.identity.id6.useremail", "frank@gamma.example.com");
user_pref("mail.identity.id6.fullName", "Frank Gamma");
user_pref("mail.identity.id7.useremail", "frank.alt@gamma.example.com");
user_pref("mail.identity.id7.fullName", "Frank Gamma (alt)");

// ---------- account17 / server7 - imap.delta.example.com - CONFIGURED BUT MISSING ----------
user_pref("mail.account.account17.identities", "id8");
user_pref("mail.account.account17.server", "server7");
user_pref("mail.server.server7.directory", "C:\\Users\\jygcn\\AppData\\Roaming\\Thunderbird\\Profiles\\measured-shape\\ImapMail\\imap.delta.example.com");
user_pref("mail.server.server7.directory-rel", "[ProfD]ImapMail/imap.delta.example.com");
user_pref("mail.server.server7.hostname", "imap.delta.example.com");
user_pref("mail.server.server7.name", "Delta Mail");
user_pref("mail.server.server7.storeContractID", "@mozilla.org/msgstore/berkeleystore;1");
user_pref("mail.server.server7.type", "imap");
user_pref("mail.server.server7.userName", "grace");
user_pref("mail.identity.id8.useremail", "grace@delta.example.com");
user_pref("mail.identity.id8.fullName", "Grace Delta");

// ---------- account18 / server8 - imap.epsilon.example.com - embedded quote in display name ----------
user_pref("mail.account.account18.identities", "id9");
user_pref("mail.account.account18.server", "server8");
user_pref("mail.server.server8.directory", "C:\\Users\\jygcn\\AppData\\Roaming\\Thunderbird\\Profiles\\measured-shape\\ImapMail\\imap.epsilon.example.com");
user_pref("mail.server.server8.directory-rel", "[ProfD]ImapMail/imap.epsilon.example.com");
user_pref("mail.server.server8.hostname", "imap.epsilon.example.com");
user_pref("mail.server.server8.name", "Heidi's \"Backup\" Mail");
user_pref("mail.server.server8.storeContractID", "@mozilla.org/msgstore/berkeleystore;1");
user_pref("mail.server.server8.type", "imap");
user_pref("mail.server.server8.userName", "heidi");
user_pref("mail.identity.id9.useremail", "heidi@epsilon.example.com");
user_pref("mail.identity.id9.fullName", "Heidi Epsilon");

// ---------- account19 / server9 - imap.zeta.example.com ----------
user_pref("mail.account.account19.identities", "id10");
user_pref("mail.account.account19.server", "server9");
user_pref("mail.server.server9.directory", "C:\\Users\\jygcn\\AppData\\Roaming\\Thunderbird\\Profiles\\measured-shape\\ImapMail\\imap.zeta.example.com");
user_pref("mail.server.server9.directory-rel", "[ProfD]ImapMail/imap.zeta.example.com");
user_pref("mail.server.server9.hostname", "imap.zeta.example.com");
user_pref("mail.server.server9.name", "Zeta Mail");
user_pref("mail.server.server9.storeContractID", "@mozilla.org/msgstore/berkeleystore;1");
user_pref("mail.server.server9.type", "imap");
user_pref("mail.server.server9.userName", "ivan");
user_pref("mail.identity.id10.useremail", "ivan@zeta.example.com");
user_pref("mail.identity.id10.fullName", "Ivan Zeta");

// ---------- account20 / server10 - Local Folders - NO IDENTITIES ----------
user_pref("mail.account.account20.identities", "");
user_pref("mail.account.account20.server", "server10");
user_pref("mail.server.server10.directory", "C:\\Users\\jygcn\\AppData\\Roaming\\Thunderbird\\Profiles\\measured-shape\\Mail\\Local Folders");
user_pref("mail.server.server10.directory-rel", "[ProfD]Mail/Local Folders");
user_pref("mail.server.server10.hostname", "Local Folders");
user_pref("mail.server.server10.name", "Local Folders");
user_pref("mail.server.server10.storeContractID", "@mozilla.org/msgstore/berkeleystore;1");
user_pref("mail.server.server10.type", "none");
user_pref("mail.server.server10.userName", "nobody");
